package grails_akka.command

/**
 * GenericCommand, with command details in the given map.
 * <br/>
 * Subclass and override the execute method for similar concrete implementation of command.
 */
public class GenericCommand implements Command
{
    // read only property, with public getter generated by Groovy, but not setter
    final Map arguments;

    public GenericCommand(Map arguments)
    {
        if (arguments == null)
            throw new IllegalArgumentException("arguments Map must be not null.");

        this.arguments = arguments;
    }

    @Override
    public void execute()
    {
        // do nothing here ... but override in subclasses
    }

}
