package grails_akka.command

import akka.actor.*


/**
 * Command that send the given message to the given actor.
 */
public class ActorCommand implements Command
{
    // read only properties, with public getter generated by Groovy, but not setter
    final ActorRef actor;
    final Serializable message;

    /**
     * Constructor
     *
     * @param actor
     * The Actor Reference, must be not null.
     *
     * @param message
     * The Serializable message to send, must be not null.
     */
    public ActorCommand(ActorRef actor, Serializable message)
    {
        if (actor == null)
            throw new IllegalArgumentException("actor must be not null.");
        if (message == null)
            throw new IllegalArgumentException("message must be not null.");

        this.actor   = actor;
        this.message = message;
    }

    @Override
    public void execute()
    {
        actor.tell(message);
    }

}
