/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package grails_akka.command

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

import org.springframework.util.Assert

import akka.actor.ActorRef

/**
 * Command that send the given message to the given actor.
 */
@EqualsAndHashCode
@ToString
class ActorCommand implements Command
{
    // read only properties, with public getter generated by Groovy, but not setter
    final ActorRef actor
    final Serializable message

    /**
     * Constructor
     *
     * @param actor
     * The Actor Reference, must be not null.
     *
     * @param message
     * The Serializable message to send, must be not null.
     */
    ActorCommand(ActorRef actor, Serializable message)
    {
        Assert.notNull(actor, "actor must be not null.")
        Assert.notNull(message, "message must be not null.")
        this.actor   = actor
        this.message = message
    }

    void execute()
    {
        actor.tell(message)
    }
}
