package grails_akka.message

import groovy.transform.*


/**
 * GenericMessage.
 * <br/>
 * Used a kind of message to send to actors.
 */
@EqualsAndHashCode
@ToString
public class GenericMessage<T> extends BaseMessage implements Serializable
{
    // read only property, with public getter generated by Groovy, but not setter
    final T message;

    public GenericMessage(T message)
    {
        this.message = message;
    }

}
